name: CICD pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t thusal123/chatgpt-clone:${{ github.sha }} .
      - name: Publish image to Docker Hub
        run: docker push thusal123/chatgpt-clone:${{ github.sha }}

  deploy:
    needs: build
    runs-on: [self-hosted, aws-ec2] # This assumes you've labeled your runner as "ec2"
    steps:
      - name: Pull image from Docker Hub
        run: docker pull thusal123/chatgpt-clone:${{ github.sha }}
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: Run Docker container
        run: docker run -d -p 80:80 --name reactContainer thusal123/chatgpt-clone:${{ github.sha }}
